### ISSUE TITLE
CMake Error at CMakeLists.txt:56 (IF)

### ISSUE THREAD

**Issue by luciferz2012** [QbProg/oce-win-bundle#10]
Dear Sir,

I am new to cmake and get an error like this:

```
CMake Error at CMakeLists.txt:56 (IF):
  if given arguments:

    "STREQUAL" "TBB"

  Unknown arguments specified
```

I googled for this error but got no direct answer.

Some information of my environment:
- Win10 Pro x64
- CMake 3.4
- OCE-Win-bundle (latest)
- Visual Studio 2015 Community Edition

**Comment by Stinkfist0** [comment]
Getting this one too. Can be fixed for the time being for example by changing the line 56 to:
```
IF("${OCE_MULTITHREAD_LIBRARY}" STREQUAL "TBB")
```

**Comment by thatcadguy** [comment]
@QbProg Getting the same as @Stinkfist0 here; CMake error then empty solution (nothing to be made) after fixing that line. Is this meant to only be used while building OCE at the same time now, i.e. can't build separately?

**Comment by Stinkfist0** [comment]
@luciferz2012 @thatcadguy OK, looking into this now. It looks like that oce-win-bundle has currently a weird default behavior of not building anything. So, pass `-DOCE_WITH_FREEIMAGE=1 -DOCE_WITH_GL2PS=1 -DBUNDLE_BUILD_FREETYPE=1` for the CMake invocation (also patch the CMakeLists.txt as as instructed above) and you should have something meaningful to build.

**Comment by Stinkfist0** [comment]
Also the CMakeLists.txt uses ${BIT} for installation directory but this is not defined anywhere.

**Comment by Stinkfist0** [comment]
Also getting this when trying to enable FreeType:
```
CMake Warning (dev) at CMakeLists.txt:85 (set):
  Cannot set "FREETYPE_INCLUDE_DIRS": current scope has no parent.
```

**Comment by thatcadguy** [comment]
"Also the CMakeLists.txt uses ${BIT} for installation directory but this is not defined anywhere."

This is probably taking from line 61 on OCE's CMakeLists.txt

**Comment by QbProg** [comment]
Dear guys,
thanks for the report. Keep in mind that oce-win-bundle is not intended to be built in a standalone way anymore, instead it needs to be built along oce itself, by putting it in the oce-win-bundle subdirectory of oce.
(I updated the instructions some time ago).
The bundle will use the same compilation options and compiler defines as oce. 
I'll check the cmake error though and let you know

**Comment by Stinkfist0** [comment]
@QbProg Where are the updated instructions? The readme and build instructions appear to be updated last time 5 years ago.

**Comment by qbprog** [comment]
In the build.MSVC.md file of the OCE repository there should be some
informations.
Basically
Git clone http://github.com/tpaviot/oce
Cd oce
Git clone http://github.com/QbProg/oce-win-bundle
CMake .
... Build...

You need to have oce/oce-win-bundle
That's it

Il giorno mer 30 dic 2015 10:10 Ali Kämäräinen notifications@github.com
ha scritto:

**Comment by Stinkfist0** [comment]
@QbProg OK. Probably good to update the instructions of this repository too. Also would be good to simply abort fast it the beginning of the CMakeLists.txt instead of completing successfully if not using the repository properly.
