### ISSUE TITLE
install bundle on windows/mingw32

### ISSUE THREAD

**Issue by tpaviot** [QbProg/oce-win-bundle#6]
The compilation goes fine with mingw32, but make install only install header files.

After installing the bundle (to D:\oce-win-bundle), I have:

* a 'include' directory with FreeImage, freetype and gl2ps subdirectories

* an empty file named 'oce-bundle-root.empty'

But I can't find any lib/dll, it seems the install process misses them.

**Comment by QbProg** [comment]
maybe it's outdated now :) the new bundle system should work with mingw too
